name: Tests

on: [push]

jobs:

    tests:
        runs-on: ubuntu-latest
        steps:
            -  uses: actions/checkout@v3

            -  uses: shivammathur/setup-php@v2
               with:
                php-version: 8.1
                coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: pwd
            -   name: Run tests
                run: ./vendor/bin/phpunit



    code_analysis:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v1"
            -   name: Run PHPStan
                run: ./vendor/bin/phpstan --error-format=github